spring:
  application:
    name: multi-data
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    username: jiwon
    url: jdbc:postgresql://127.0.0.1:5432/cloud
    password: 